---
- name: Ensure EPEL repo is installed
  yum:
    name: epel-release
    state: installed
  become: True
  when: "{{ os_shade_install_epel | bool }}"

- name: Ensure required packages are installed
  yum:
    name: "{{ item }}"
    state: installed
  become: True
  with_items: "{{ os_shade_package_dependencies }}"
  when: "{{ os_shade_install_package_dependencies | bool }}"

- name: Ensure the latest version of pip is installed
  pip:
    name: "{{ item.name }}"
    state: latest
    virtualenv: "{{ os_shade_venv or omit }}"
  with_items:
    - { name: pip }

- name: Ensure required Python packages are installed
  pip:
    name: "{{ item.name }}"
    version: "{{ item.version or omit }}"
    state: present
    virtualenv: "{{ os_shade_venv or omit }}"
  with_items:
    - name: shade
      version: "{{ os_shade_version }}"
